#change server port
server:  port: 2020

#logging:
#  level:
#    org.springframework.web: ERROR
#    com.chauhansoft.controller: DEBUG
#    #  pattern:#    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
#    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"#  file:#    path: src/main/resources/log/
#    name: src/main/resources/log/employee-log.log